### ISSUE TITLE
[Angular] ReferenceError: document is not defined

### ISSUE THREAD

**Issue by maxtanchangyong** [rcbyr/keen-slider#407]

**Comment by mercuriousreign** [comment]
Got the same problem here:

```
Application bundle generation complete. [0.157 seconds]

Page reload sent to client(s).
ReferenceError: document is not defined
    at eval (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:593:38)
    at eval (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:634:115)
    at k.drag (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:636:8)
    at y (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:637:6)
    at main (/home/username/workfolder/afolder/projectname/src/app/products/products.component.ts:71:19)
    at callHookInternal (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:16032:10)
    at callHook (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:16047:7)
    at callHooks (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:16021:9)
    at executeInitAndCheckHooks (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:15990:5)
    at refreshView (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:20947:11)
ReferenceError: document is not defined
    at eval (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:593:38)
    at eval (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:634:115)
    at k.drag (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:636:8)
    at y (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/keen-slider.js:637:6)
    at main (/home/username/workfolder/afolder/projectname/src/app/products/products.component.ts:72:28)
    at callHookInternal (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:16032:10)
    at callHook (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:16047:7)
    at callHooks (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:16021:9)
    at executeInitAndCheckHooks (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:15990:5)
    at refreshView (/home/username/workfolder/afolder/projectname/.angular/cache/18.1.3/vite/deps_ssr/chunk-3PQRU26X.js:20947:11)
```
Angular CLI: 18.1.3
Node: 18.19.1
Package Manager: npm 10.2.4

**Comment by oikalyptus** [comment]
We’ve got the same problem in an SSR context. I will try to initialize the slider on the client only. If I find a solution that works for me, I will post it here.
